# Generated by Django 3.2.7 on 2021-10-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
