# Generated by Django 3.2.7 on 2021-11-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20211115_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='slides')),
            ],
        ),
    ]
