from django.contrib import admin
from django.urls import path
from school import views

urlpatterns = [
    path('', views.start),
    path('login', views.loginPage),
    path('logout', views.logoutPage),
    path('home', views.home),
    path('upload', views.upload),
    path('upload1', views.upload1),
    path('upload2', views.upload2),
    path('upload3', views.upload3),
    path('upload4', views.upload4),
    path('addevent', views.addevent),
    path('deleteevent/<str:pk>', views.deleteevent, name='deleteevent'),
    path('news/<str:pk>', views.news, name='news'),
    path('admin_news/<str:pk>', views.admin_view, name='admin_news'),
    path('about-overview', views.aboutoverview),
    path('about-infrastructure', views.aboutinfrastructure),
    path('about-management', views.aboutmanagement),
    path('about-campuslife', views.aboutcampuslife),
    path('about-gallery', views.aboutgallery),
    path('academics-overview', views.academicsoverview),
    path('academics-board', views.academicsboard),
    path('academics-subjects', views.academicssubjects),
    path('general', views.general),
    path('laboratory', views.laboratory),
    path('hostel', views.hostel),
    path('sports', views.sports),
    path('bus', views.bus),
    path('admission-procedure', views.admissionprocedure),
    path('required-documentation', views.requireddocumentation),
    path('parent-feedback', views.parentfeedback),
    path('FAQ', views.FAQ),
    path('know-your-child', views.knowyourchild),
    path('career-zone', views.career_zone, name='career-zone'),
    path('contact', views.contact),
]